apiVersion: v1
kind: ConfigMap
metadata:
  name: splitwise-config
  namespace: splitwise
data:
  NODE_ENV: "production"
  PORT: "5000"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  MONGO_HOST: "mongodb-service"
  MONGO_DB: "splitwise"